port: 4000

# Site settings
title: The Retros
email: retrocessionist.improv@gmail.com
description: "The Retros - Improv Comedy in Alexandria, VA"

shows:
- date: March 7, 2026
  time: 8:00pm
  title: "Retros in Bloom"
  location: 600 Wolfe St, Alexandria, VA 22314
- date: April 25, 2026
  time: 8:00pm
  title: "April Comedy May Surprise"
  location: 600 Wolfe St, Alexandria, VA 22314
- date: June 13, 2026
  time: 8:00pm
  title: "Start Your Summer with the Retros"
  location: 600 Wolfe St, Alexandria, VA 22314
past_shows:
- date: November 22, 2025
  time: 8:00pm
  title: "Improv Cornucopia"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-comedy-show-with-the-retros-tickets-1752184283359?aff=website
sold_out: True
- date: October 11, 2025
  time: 8:00pm
  title: "The Retros Halloween Show"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-comedy-show-with-the-retros-tickets-1752183611349?aff=website
  sold_out: True
- date: May 17, 2025
  time: 8:00pm
  title: "May we interest you in some comedy?"
  url: https://www.eventbrite.com/e/improv-comedy-show-with-the-retros-tickets-1353541782909?aff=website
  location: 600 Wolfe St, Alexandria, VA 22314
- date: March 8, 2025
  time: 8:00pm
  title: "Spring forward with laughter!"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-comedy-show-with-the-retros-tickets-1252947803609?aff=website
  sold_out: True
- date: January 18, 2025
  time: 8:00pm
  title: "New Year's Extravaganza"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-comedy-show-with-the-retros-tickets-1141765965739?aff=website
  sold_out: True
- date: Nov 16, 2024
  time: 8:00pm
  title: "Thanks For The Suggestion"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/free-improv-comedy-show-with-the-retros-tickets-1074236232489?aff=website
  sold_out: True
- date: Oct 5, 2024
  time: 8:00pm
  title: "Spooky Season with the Retros"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-comedy-show-with-the-retros-tickets-1026572464877?aff=website
  sold_out: False
- date: August 17, 2024
  time: 8:00pm
  title: "Summer's End with the Retros"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-comedy-show-with-the-retros-tickets-974801757297?aff=website
  sold_out: True
- date: June 29, 2024
  time: 8:00pm
  title: "June Lightning Strikes Retros Twice"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/free-improv-comedy-show-with-the-retros-tickets-928537208787?aff=website
  sold_out: True
- date: June 15, 2024
  time: 8:00pm
  title: "June is the Most Retros Month of All"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-comedy-show-in-alexandria-va-tickets-909148185697?aff=website
  sold_out: True
- date: April 27, 2024
  time: 8:00pm
  title: "April Showers Make Retros Flowers"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/free-improv-show-in-alexandria-tickets-882224345767
  sold_out: True
- date: March 9, 2024
  time: 8:00pm
  title: "Spring into Spring with The Retros"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/free-improv-comedy-in-alexandria-tickets-853806396917
  sold_out: True
- date: January 27, 2024
  time: 8:00pm
  title: "Defrost with The Retros"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/free-improv-comedy-in-alexandria-tickets-797998744727
  sold_out: True
- date: December 9, 2023
  time: 8:30pm
  title: "Retros Improv: Sleighin' It!"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/retros-improv-sleighin-it-tickets-769215182317
  sold_out: False
- date: October 7, 2023
  time: 8:00pm
  title: "The Retros: Halloween Edition - Improv in Old Town Alexandria"
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/the-retros-halloween-edition-tickets-727600371297
  sold_out: False
- date: February 11, 2023
  time: 8:00pm
  title: Retros Valentine's Day - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/free-improv-show-tickets-535046026067
  sold_out: True
- date: November 12, 2022
  time: 8:00pm
  title: A Retros Thanksgiving - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/free-improv-show-in-alexandria-tickets-462190824197
  sold_out: False
- date: October 8, 2022
  time: 8:00pm
  title: The Retros Halloween Show - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/free-improv-show-in-alexandria-tickets-407130727967
  sold_out: True
- date: April 30, 2022
  time: 8:00pm
  title: We're Back! Live, Free Improv in Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/were-back-live-free-improv-in-alexandria-tickets-326352558287
- date: June 13, 2020
  time: 9:00pm
  title: The Retros - Improv Night in Your Home
  location: Online
  url: https://www.facebook.com/RetrosImprov/live
- date: May 9, 2020
  time: 8:00pm
  title: The Retros - Improv Night in Your Home
  location: Online
  url: https://www.facebook.com/RetrosImprov/live
- date: February 15, 2020
  time: 8:00pm
  title: The Retros - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-night-in-old-town-alexandria-tickets-93703077427
  sold_out: True
- date: February 1, 2020
  time: 8:00pm
  title: The Retros at the Comedy NOVA Launch Party
  location: Summers Restaurant, 1520 North Courthouse Road, Arlington, VA 22201
  url: https://www.eventbrite.com/e/comedy-nova-launch-party-tickets-90464400457
- date: November 16, 2019
  time: 8:00pm
  title: The Retros - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-night-in-old-town-alexandria-tickets-81089176911
  sold_out: True
- date: October 5, 2019
  time: 8:00pm
  title: The Retros - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-night-in-old-town-alexandria-tickets-74317043277
  sold_out: True
- date: August 24, 2019
  time: 8:00pm
  title: The Retros - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-night-in-old-town-alexandria-tickets-69230266591
  sold_out: True
- date: July 6, 2019
  time: 8:00pm
  title: The Retros - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-night-in-old-town-alexandria-tickets-64002717852
  sold_out: True
- date: May 25, 2019
  time: 8:00pm
  title: The Retros - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-night-in-old-town-alexandria-tickets-61948455498
  sold_out: True
- date: April 5, 2019
  time: 8:00pm
  title: The Retros - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-night-in-old-town-alexandria-tickets-58287032082
  sold_out: True
- date: February 9, 2019
  time: 8:00pm
  title: The Retros - Improv in Old Town Alexandria
  location: 600 Wolfe St, Alexandria, VA 22314
  url: https://www.eventbrite.com/e/improv-night-in-old-town-alexandria-tickets-55596762413
  sold_out: True

# Team names, titles and social links
people:
- name: Arhan
  pic: arhan
- name: Dan
  pic: dan
- name: Jeff
  pic: jeff
- name: Julie
  pic: julie
- name: Kate
  pic: kate
- name: Keely
  pic: keely
- name: Sarah
  pic: sarah-500px
- name: Yotam
  pic: yotam

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#  - title: twitter
#    url: http://twitter.com/RetrosImprov
social:
  - title: facebook
    url: https://www.facebook.com/RetrosImprov/

# Postal address (add as many lines as necessary)
address:
  - line: The Little Theatre of Alexandria
  - line: 600 Wolfe Street
  - line: Alexandria, VA 22314

# Build settings
markdown: kramdown
permalink: pretty
